### ISSUE TITLE
Test Cases Failing

### ISSUE THREAD

**Issue by Rajashekar25** [su2code/TestCases#134]
Hi, I have installed SU2 on Linux (WSL). Ubuntu 22.04.1 LTS 
I have run test cases using python file. majority of test cases passed. But few test cases are failing.  
User defined options while installing are Optimization: 3, enable-autodiff: true, enable-directdiff: true, enable-tests: true, enable-pywrapper: true 
Failed Test cases: airfoil_fsi_rbf, ploar_naca0012, contadj_euler_py, shape_opt_euler_py, opt_multiobj1surf_py, opt_2surf1obj_py,  pywrapeer_* files
Please help on how to fix this issue.

**Comment by pcarruscag** [comment]
If the changes are small it can be due to compiler differences.

**Comment by Rajashekar25** [comment]
Hi @pcarruscag, Thanks for your response.
Few points.

I didn't install scipy. Post installing that pywrapper test cases passed. 
I am using gcc-11.2 compiler. 
As you mentioned, in some cases difference in answers is slightly more tolerance; that's why test cases failed. Ex: opt_2surf1obj_py, opt_multiobj1surf_py, airfoil_fsi_rbf, polar_naca0012.

I didn't understand the output of contadj_multi_py. It is showing as failed. Similarly contadj_euler_py. 

==================== Start Test: contadj_multi_py ====================
/root/SU2/TestCases/cont_adj_euler/wedge
--- of_grad_combo.dat.ref       Sat Jun 17 12:32:57 2023
+++ of_grad_combo.dat   Sat Jul 29 12:53:07 2023
@@ -1,5 +1,5 @@
 VARIABLES="VARIABLE"      , "GRADIENT"      , "FINDIFF_STEP"
-          0               , 0.00766235      , 0.0001
-          1               , 0.00499567      , 0.0001
-          2               , 0.00249665      , 0.0001
-          3               , 0.000904607     , 0.0001
+          0               , 0.00776779      , 0.0001
+          1               , 0.00485872      , 0.0001
+          2               , 0.00242841      , 0.0001
+          3               , 0.000890284     , 0.0001
CPU architecture=x86_64
test duration: 0.02 min
==================== End Test: contadj_multi_py ====================

For contadj_wedge, diff was more. 
execution command: SU2_CFD inv_wedge_ROE.cfg.autotest > inv_wedge_ROE.cfg.log 2>&1
ERROR: Difference between computed input and test_vals exceeded tolerance. TOL=0.000010
CPU architecture=x86_64
test_iter=10
test_vals (stored): 2.872691, -2.755572, 853000.000000, 0.000000
sim_vals (computed): 2.872691, -2.755572, 877460.000000, -0.000000
delta_vals: 0.000000, 0.000000, 24460.000000, 0.000000
test duration: 0.00 min
==================== End Test: contadj_wedge ====================
slight diff for below test case. 
execution command: SU2_CFD inv_NACA0012.cfg.autotest > inv_NACA0012.cfg.log 2>&1
ERROR: Difference between computed input and test_vals exceeded tolerance. TOL=0.001000
CPU architecture=x86_64
test_iter=5
test_vals (stored): -9.289565, -14.563861, 0.300920, 0.019552
sim_vals (computed): -1.279610, -6.438595, 0.161190, 0.019552
delta_vals: 8.009955, 8.125266, 0.139730, 0.000000
test duration: 0.00 min
==================== End Test: contadj_naca0012 ====================

Thanks.
