### ISSUE TITLE
The Turek and Hron Benchmark problem

### ISSUE THREAD

**Issue by DURAI04** [su2code/TestCases#21]
Hi I am new one for SU2. Now I am working in the filed of SU2- PreCICE-Calculix Coupling. I did all software installations in ubuntu 16.04. After that i test the flap case https://github.com/precice/precice/wiki/FSI-tutorial which is working fine. Now i need to validate the one problem.For that regard i used for the following reference case. It is not working properly. Can you please help me?
[su2_calcu.tar.gz](https://github.com/su2code/TestCases/files/2279969/su2_calcu.tar.gz)
![selection_021](https://user-images.githubusercontent.com/17636077/43988839-b3cd90ce-9d5b-11e8-9999-a9fd7164de3f.png)

**Comment by economon** [comment]
Hi @DURAI04 : thanks for your interest! Unfortunately, this is a fairly static repository for meshes and data files for the SU2 suite only. I think your question is better suited for the SU2 CFD Online forum here: https://www.cfd-online.com/Forums/su2/. Please post your question there. Closing this issue for now.
