### ISSUE TITLE
Hotspots of SU2

### ISSUE THREAD

**Issue by psgmech** [su2code/TestCases#77]
Hi everyone. I am working in SU2. I want to find the hotspot of Euler solver code () . 

Expecting both Command line profile methods and GUI profiler suggestion from you.

completed running a Test case **Inviscid Bump** in a Channel (A simulation of internal, inviscid flow through a 2D geometry)

Did command line profiling a nQueen Problem, need to do the same for SU2 while running a test case like Inviscid Bump

![6](https://user-images.githubusercontent.com/91520214/135038760-ab986cf3-df8a-42a0-a459-91fb1cab26c9.png)

**Comment by TobiKattmann** [comment]
Hi @psgmech , please open this as a discussion over at https://github.com/su2code/SU2/discussions . This is not really the best place to get interaction :) If you are interested to join the SU2 developers meeting to talk a bit about your ideas etc you are more than welcome. Each Wednesday https://meet.jit.si/SU2_Devmeeting at 4pm CET time. 

best Tobi

**Comment by psgmech** [comment]
Noted. We will try to join Wednesday meetings to talk further.

**Comment by psgmech** [comment]
> Is this the right meeting link


https://meet.jit.si/SU2_Devmeeting
